In [287]:
''' Ejercicio 1 - 2do Parcial'''
''' Taboada Rodas Oscar '''

' Taboada Rodas Oscar '

In [288]:
import os
import numpy as np
from matplotlib import pyplot
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [289]:
data = pd.read_csv('DATASET.csv')
data.head()

Marca  Modelo (Ej: 2021, 2016)  Tipo  Numero de puertas  Transmision   \
0      2                     2011     2                  4             2   
1      2                     2016     3                  4             1   
2      2                     2016     2                  4             1   
3      2                     2016     2                  4             1   
4      2                     2017     2                  4             1   

   Tipo Combustible   Estado del vehiculo  Costo en $us  
0                  1                    2         99856  
1                  1                    2        977011  
2                  1                    2        977011  
3                  1                    1         95546  
4                  2                    2        948275

In [291]:
# data = data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1161 entries, 0 to 1160
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Marca                    1161 non-null   int64
 1   Modelo (Ej: 2021, 2016)  1161 non-null   int64
 2   Tipo                     1161 non-null   int64
 3   Numero de puertas        1161 non-null   int64
 4   Transmision              1161 non-null   int64
 5   Tipo Combustible         1161 non-null   int64
 6   Estado del vehiculo      1161 non-null   int64
 7   Costo en $us             1161 non-null   int64
dtypes: int64(8)
memory usage: 81.6 KB


In [292]:
X = data[['Marca', 'Modelo (Ej: 2021, 2016)', 'Tipo', 'Numero de puertas', 'Estado del vehiculo']].to_numpy()
X


array([[   2, 2011,    2,    4,    2],
       [   2, 2016,    3,    4,    2],
       [   2, 2016,    2,    4,    2],
       ...,
       [  17, 2001,    2,    5,    2],
       [  12, 1985,    1,    4,    2],
       [  12, 1985,    1,    4,    2]], dtype=int64)

In [293]:
y = data['Costo en $us'].to_numpy()
y

array([ 99856, 977011, 977011, ...,   2001,   2000,   2000], dtype=int64)

In [295]:
def  normalizarCaracteristicas(X):
    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (X - mu) / sigma
    
    return X_norm, mu, sigma

In [296]:
X_norm, mu, sigma = normalizarCaracteristicas(X)

print(X)
print('Media calculada:', mu)
print('Desviación estandar calculada:', sigma)
print(X_norm)

[[   2 2011    2    4    2]
 [   2 2016    3    4    2]
 [   2 2016    2    4    2]
 ...
 [  17 2001    2    5    2]
 [  12 1985    1    4    2]
 [  12 1985    1    4    2]]
Media calculada: [1.20551249e+01 2.01165202e+03 1.92161929e+00 4.30060293e+00
 1.85701981e+00]
Desviación estandar calculada: [7.88867809 7.39062759 0.81325547 0.84147935 0.35005265]
[[-1.27462736 -0.08822311  0.09637895 -0.3572315   0.40845339]
 [-1.27462736  0.58830943  1.32600486 -0.3572315   0.40845339]
 [-1.27462736  0.58830943  0.09637895 -0.3572315   0.40845339]
 ...
 [ 0.6268319  -1.44128817  0.09637895  0.8311518   0.40845339]
 [-0.00698785 -3.60619227 -1.13324697 -0.3572315   0.40845339]
 [-0.00698785 -3.60619227 -1.13324697 -0.3572315   0.40845339]]


In [297]:
m, n = X.shape
X_ready = np.concatenate([np.ones((m, 1)), X_norm], axis=1)

In [298]:
def calcularCosto(X, y, theta):
    m = y.size
    J = 0
    h = np.dot(X, theta)
    # print(h)
    J = (1/(2 * m)) * np.sum(np.square(h - y))
    return J

In [299]:
# theta=np.array([0.1, 1.0, 0.1, 0.1, 1.0, 0.1])
# theta = np.random.rand(6)
theta = np.zeros(6)
JJ = calcularCosto(X_ready, y, theta)
print(f"con theta:{ theta } se obtiene un costo de: {JJ}")

con theta:[0. 0. 0. 0. 0. 0.] se obtiene un costo de: 105139717340.24721


In [300]:
def calcularDescensoGradiente(X, y, theta, alpha, numero_iteraciones):
      m = y.shape[0]
      theta = theta.copy()
      J_historico = []

      for i in range(numero_iteraciones):
        theta = theta - (alpha / m) * (np.dot(X, theta) - y).dot(X)
        J_historico.append(calcularCosto(X, y, theta))
        return theta, J_historico

In [301]:
theta = np.zeros(6)

num_ite = 100000
alpha = 0.001

theta, J_historico = calcularDescensoGradiente(X_ready, y, theta, alpha, num_ite)
print(f"los valores de theta calculados son: { theta }")
print(f"con un costo de: { J_historico[-1]} ")


los valores de theta calculados son: [50.05771921  2.13789029  1.81660774 -1.98871556 14.11613062  5.1388244 ]
con un costo de: 105136975444.59972 


In [302]:
y_pred = np.dot([1, 12, 2016, 1, 4, 1], theta)
print(y_pred)

3797.608237682794


In [303]:
def CalcularthetaEcuacionNormal(X, y):
    theta = np.zeros(X.shape[1])
    theta = np.dot(np.dot(np.linalg.inv(np.dot(X.T,X)),X.T),y)
    return theta

In [304]:
X_ren = np.concatenate([np.ones((m, 1)), X], axis=1)

In [305]:
theta = CalcularthetaEcuacionNormal(X_ren, y);
print(f"los valores de theta calculados son: { theta }")

los valores de theta calculados son: [-4.90592593e+05  3.92424650e+02  2.16253190e+02  7.21908984e+02
  1.65410004e+04  1.52771165e+04]


In [306]:
X_array = [1, 12, 2016, 1, 4, 1]
price = np.dot(X_array, theta)

print('Precio de un automovil (usando la ecuación de la normal): ${:.0f}'.format(price))

Precio de un automovil (usando la ecuación de la normal): $32246
